#!/bin/bash
#
# by Emanuele Tomasi <targzeta@gmail.com>

# Calcola la percentuale di 'partial' sul 'total'. Il risultato viene settato
# nella variabile il cui nome è dato dal terzo argomento della funzione.
#
# Nota: viene passato il nome della variabile da settare per evitare il command
# substition. Questo perché implicherebbe l'esecuzione della funzione in una
# subshell, che rallenterebbe di molto lo script, visto la quantità di volte
# che viene chiamata!
function _perc() {
  local partial=$1
  local total=$2
  local var_name=$3

  local perc=0
  (($total != 0)) && let perc=partial*100/total

  let $var_name=perc
}

function _calc_data() {
  old_tamponi=0
  old_dimessi=0
  old_deceduti=0
  skipped_first_line=0
  while IFS=',' read data ricoverati terapia_intensiva ospedalizzati \
           isolamento positivi nuovi_positivi nuovi_casi dimessi deceduti \
           casi tamponi dummy
  do
    let nuovi_tamponi=tamponi-old_tamponi
    old_tamponi=$tamponi

    let nuovi_dimessi=dimessi-old_dimessi
    old_dimessi=$dimessi

    let nuovi_deceduti=deceduti-old_deceduti
    old_deceduti=$deceduti

    # Se vanno saltati dei giorni, il primo ciclo del loop viene fatto solo per
    # settare i valori "old_".
    if (($FROM_DAY != 1 && $skipped_first_line == 0))
    then
      skipped_first_line=1
      continue
    fi

    _perc nuovi_positivi nuovi_tamponi 'incremento_positivi'
    _perc nuovi_casi nuovi_tamponi 'incremento_casi'

    _perc ricoverati ospedalizzati 'perc_ricoverati'
    _perc terapia_intensiva ospedalizzati 'perc_terapia_intensiva'

    _perc ospedalizzati positivi 'perc_ospedalizzati'
    _perc isolamento positivi 'perc_isolamento'

    _perc positivi casi 'perc_positivi'
    _perc dimessi casi 'perc_dimessi'
    _perc deceduti casi 'perc_deceduti'

    echo "$data
          $nuovi_tamponi
          $nuovi_dimessi
          $nuovi_deceduti
          $nuovi_positivi
          $nuovi_casi
          $incremento_positivi
          $incremento_casi
          $casi
          $positivi
          $perc_positivi
          $dimessi
          $perc_dimessi
          $deceduti
          $perc_deceduti
          $ospedalizzati
          $perc_ospedalizzati
          $isolamento
          $perc_isolamento
          $ricoverati
          $perc_ricoverati
          $terapia_intensiva
          $perc_terapia_intensiva
         " | tr -d ' ' | paste -s -d ','
  done
}

# data,
# stato,
# ricoverati_con_sintomi,
# terapia_intensiva,
# totale_ospedalizzati,
# isolamento_domiciliare,
# totale_positivi,
# variazione_totale_positivi,
# nuovi_positivi,
# dimessi_guariti,
# deceduti,
# totale_casi,
# tamponi,
# note_it,
# note_en
function italia() {
  cut -d',' -f1,3- ${DATA_DIR}/${FILE_ITALIA} |\
    sed -n "$(($FROM_DAY+1)),\$p" |\
  _calc_data
}

# data,
# stato,
# codice_regione,
# denominazione_regione,
# lat,
# long,
# ricoverati_con_sintomi,
# terapia_intensiva,
# totale_ospedalizzati,
# isolamento_domiciliare,
# totale_positivi,
# variazione_totale_positivi,
# nuovi_positivi,
# dimessi_guariti,
# deceduti,
# totale_casi,
# tamponi,
# note_it,
# note_en
function regione() {
 local regione="$1"
 grep ",${regione}," ${DATA_DIR}/${FILE_REGIONI} |\
   sed -n "${FROM_DAY},\$p" |\
   cut -d',' -f1,7- |\
   _calc_data
}

function provincia() {
  local provincia="$1"
  grep ",${provincia}," ${DATA_DIR}/${FILE_PROVINCE} |\
    sed -n "${FROM_DAY},\$p" |\
    cut -d',' -f1,10 |\
    (
      old_casi=0
      while IFS=',' read data casi
      do
        let nuovi_casi=casi-old_casi
        echo "$data,$nuovi_casi,$casi"
        old_casi=$casi
      done
    )
}

# Calcola e ritorna il giorno da cui partire per mostrare esattamente il numero
# di giorni passati in input. Da usare per settare la variabile FROM_DAY.
function _get_lastN_days() {
  local window=$1
  local today=$(date '+%j')
  local first_day=$(date -d '2020-02-20' '+%-j')

  echo $(($today - (($today - $first_day) + $window)))
 }

function _check_requirements() {

  error=0
  for req in cut sed grep gnuplot stat git mkdir
  do
    if ! type $req >& /dev/null
    then
      error=1
      echo "$req: comando mancante!"
    fi
  done

  if (( $error == 1 ))
  then
    echo -e "\nUno o più comandi mancanti. Non posso procedere :-(!"
    exit 1
  fi
}

function _main() {
  ZONE="$1"

  if [[ "$ZONE" == "Italia" ]]
  then
    gp_file=multiple.gp
    fun=italia
  elif grep -q ",${ZONE}," ${DATA_DIR}/${FILE_REGIONI}
  then
    gp_file=multiple.gp
    fun=regione
  elif grep -q ",${ZONE}," ${DATA_DIR}/${FILE_PROVINCE}
  then
    gp_file=single.gp
    fun=provincia
  else
    echo "Input non trovato: ${ZONE}"
    return
  fi

  DAT_FILE="${TMP_DIR}/${ZONE}.dat"
  ${fun} "${ZONE}" > "$DAT_FILE"

  UPDATE_DATE=$(tail -n1 "$DAT_FILE" |\
                  sed -E 's;^([0-9]*)-([0-9]*)-([0-9]*)T([^,]*).*;\3/\2/\1 \4;')

  gp_dir=templates
  outfile=${TMP_DIR}/current.gp
  cat ${gp_dir}/common.gp ${gp_dir}/${gp_file} |\
    sed "s|#ZONE#|${ZONE}|
         s|#FILE#|${DAT_FILE}|
         s|#UPDATE#|${UPDATE_DATE}|
        " > $outfile

  if [ $gp_file = 'multiple.gp' ]
  then
    sed_command=''
    IFS=',' read -a values < <(tail -n1 "$DAT_FILE" | cut -d',' -f9-)
    for i in ${!values[*]}
    do
      sed_command+="s|#${i}#|${values[$i]}|;"
    done
    sed -i "${sed_command}" $outfile
  fi

  gnuplot -font -misc-fixed-medium-r-*-*-*-100-*-*-*-*-iso10646-1 -p $outfile
}

# Aggiorna i dati dal repository della protezione civile, aggiornati tutti i
# giorni alle 18:30. I vengono scaricati:
# - quando il file di andamento nazionale non esiste (prima volta)
# - se siamo oltre le 18:30 di oggi e il file di andamento nazionale è
#   antecedente le 18:30
function _update_data() {
  local check_file=${DATA_DIR}/${FILE_ITALIA}
  local today_update=$(date -d 'today 18:30' '+%s')
  local now=$(date '+%s')

  [ -f $check_file ] \
    && local last_update=$(stat -c '%Y' ${DATA_DIR}/${FILE_ITALIA})

  if [ ! -f $check_file ] \
       || [ \( $now -gt $today_update -a $last_update -lt $today_update \) ]
  then
      echo "Download dati!"
      git submodule update --init --remote
  fi
}

DATA_DIR=data
FILE_ITALIA=dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
FILE_REGIONI=dati-regioni/dpc-covid19-ita-regioni.csv
FILE_PROVINCE=dati-province/dpc-covid19-ita-province.csv

FROM_DAY=$(_get_lastN_days 34) # Parte dal giorno FROM_DAY + 1
TMP_DIR=tmp

mkdir -p $TMP_DIR

_check_requirements
_update_data

if [ -z "$1" ]
then
  _main "Italia"
else
  for zone in "$@"
  do
    _main "$zone"
  done
fi
